// Generated by CoffeeScript 1.3.3
(function() {
  var fruit, fruits, _i, _len;

  fruits = ["apple", "orange", "banana"];

  for (_i = 0, _len = fruits.length; _i < _len; _i++) {
    fruit = fruits[_i];
    console.log(fruit);
  }

}).call(this);
