// Generated by CoffeeScript 1.3.3
(function() {
  var getFullName, hello;

  hello = function(name) {
    return console.log("Hello, " + name + "!");
  };

  getFullName = function(firstName, lastName) {
    return "" + firstName + " " + lastName;
  };

}).call(this);
