// Generated by CoffeeScript 1.3.3
(function() {
  var fruits, name, upperFruits;

  fruits = ["apple", "orange", "pineapple"];

  upperFruits = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = fruits.length; _i < _len; _i++) {
      name = fruits[_i];
      _results.push(name.toUpperCase());
    }
    return _results;
  })();

  console.log(upperFruits);

}).call(this);
