// Generated by CoffeeScript 1.3.3
(function() {
  var getPrice;

  getPrice = function(price, discountPercent) {
    if (discountPercent == null) {
      discountPercent = 0;
    }
    return price * (1 - discountPercent / 100);
  };

  getPrice(1000);

  getPrice(1000, 30);

  getPrice(1000, 50);

}).call(this);
