// Generated by CoffeeScript 1.3.3
(function() {
  var countdown, digits, months;

  months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

  countdown = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0];

  digits = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

}).call(this);
