// Generated by CoffeeScript 1.3.3
(function() {
  var func, i, _i;

  for (i = _i = 1; _i <= 3; i = ++_i) {
    func = (function(i) {
      return function() {
        return console.log(i);
      };
    })(i);
    setTimeout(func, 1000);
  }

}).call(this);
