// Generated by CoffeeScript 1.3.3
(function() {
  var getKey;

  getKey = (function() {
    var _key;
    _key = "AllYourBase";
    return function() {
      return _key;
    };
  })();

  console.log(getKey());

  console.log(typeof _key);

}).call(this);
