// Generated by CoffeeScript 1.3.3
(function() {
  var Bird, birdA;

  Bird = (function() {

    function Bird() {}

    Bird.prototype.nickname = "ある鳥";

    Bird.prototype.sing = function() {
      return console.log("チュンチュン");
    };

    return Bird;

  })();

  birdA = new Bird;

  birdA.sing();

}).call(this);
