// Generated by CoffeeScript 1.3.3
(function() {
  var Bird, birdA;

  Bird = (function() {

    function Bird() {
      this.nickname = "ある鳥";
    }

    return Bird;

  })();

  birdA = new Bird;

  console.log(birdA.nickname);

  delete birdA.nickname;

  console.log(birdA.nickname);

}).call(this);
