// Generated by CoffeeScript 1.3.3
(function() {
  var Animal,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Animal = (function() {
    var Cat, Dog, animalA, hachi, michael;

    Animal.prototype.sound = "";

    Animal.prototype.name = "ある動物";

    function Animal(name) {
      if (name != null) {
        this.name = name;
      }
    }

    Animal.prototype.say = function(text) {
      return console.log("" + this.name + "  「" + this.sound + text + "」");
    };

    Cat = (function(_super) {

      __extends(Cat, _super);

      function Cat() {
        return Cat.__super__.constructor.apply(this, arguments);
      }

      Cat.prototype.sound = "ニャア。";

      return Cat;

    })(Animal);

    Dog = (function(_super) {

      __extends(Dog, _super);

      function Dog() {
        return Dog.__super__.constructor.apply(this, arguments);
      }

      Dog.prototype.sound = "ワン！";

      return Dog;

    })(Animal);

    animalA = new Animal;

    animalA.say("天気がいいなあ");

    michael = new Cat("マイケル");

    hachi = new Dog("ハチ");

    michael.say("今日はお出かけですか？");

    hachi.say("天気がいいのでうちの主人と散歩に行きます");

    return Animal;

  })();

}).call(this);
