// Generated by CoffeeScript 1.3.3
(function() {
  var Animal, Cat, snowbell,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Animal = (function() {

    function Animal(name) {
      if (name != null) {
        this.name = name;
      }
    }

    Animal.prototype.say = function(text) {
      return console.log("「" + text + "」");
    };

    return Animal;

  })();

  Cat = (function(_super) {

    __extends(Cat, _super);

    function Cat(name) {
      Cat.__super__.constructor.call(this, name);
      this.type = "ペルシャ";
    }

    Cat.prototype.say = function(text) {
      Cat.__super__.say.call(this, text);
      return console.log("と" + this.type + "ネコの" + this.name + "は言いました。");
    };

    return Cat;

  })(Animal);

  snowbell = new Cat("スノーベル");

  snowbell.say("何か頂戴。");

}).call(this);
